### ISSUE TITLE
Improve package not found message

### ISSUE THREAD

**Issue by ndrwrbgs** [CommonBuildToolset/CBT.Core#113]
The current message is not very clear:

```
The "GenerateNuGetProperties" task failed unexpectedly.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at CBT.NuGet.Internal.NuGetPackageReferenceProjectParser.TryGetPackages(String packageConfigPath, PackageRestoreData packageRestoreData, IEnumerable`1& packages)
   at CBT.NuGet.Internal.NuGetPropertyGenerator.<>c__DisplayClass5_2.<Generate>b__0(INuGetPackageConfigParser i)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CBT.NuGet.Internal.NuGetPropertyGenerator.Generate(String outputPath, String propertyVersionNamePrefix, String propertyPathNamePrefix, PackageRestoreData restoreData)
   at CBT.NuGet.Tasks.GenerateNuGetProperties.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by jeffkl** [comment]
This issue was moved to CommonBuildToolset/CBT.Modules#225
